#!/usr/bin/env bash

# Copyright 2019 The Grin Developers
# Modifications Copyright 2019 The Gotts Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script contains release-related jobs.

# Redeclare CI and VCP specific environment variables
# to make future migration to other providers easier.
readonly JOB_ID="${TRAVIS_JOB_ID}"
readonly OS_NAME="${TRAVIS_OS_NAME}"
readonly TEST_RESULT="${TRAVIS_TEST_RESULT}"

# To avoid uploading garbage files when 'release' job not enabled.
cargo clean

case "${CI_JOB}" in
    "release")
        # The release can only be triggered after successful completion of all tests.
        [[ "${TEST_RESULT}" != 0 ]] && exit 1

        readonly REPO_TAG="$(git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD)"

        case "${OS_NAME}" in
            "linux")
                cargo clean && \
                cargo build --release || exit 1
                readonly ARCHIVE_CMD="tar zcf"
                readonly BIN_SUFFIX=""
                readonly PKG_NAME="gotts-${REPO_TAG}-${JOB_ID}-linux-amd64"
                readonly PKG_SUFFIX=".tgz"
                ;;

            "osx")
                brew update
                cargo clean && \
                cargo build --release || exit 1
                readonly ARCHIVE_CMD="tar zcf"
                readonly BIN_SUFFIX=""
                readonly PKG_NAME="gotts-${REPO_TAG}-${JOB_ID}-osx"
                readonly PKG_SUFFIX=".tgz"
                ;;

            "windows")
                cargo clean && \
                cargo build --release || exit 1
                readonly ARCHIVE_CMD="7z a -tzip"
                readonly BIN_SUFFIX=".exe"
                readonly PKG_NAME="gotts-${REPO_TAG}-${JOB_ID}-win-x64"
                readonly PKG_SUFFIX=".zip"
                ;;

            *)
                printf "Error! Unknown \$OS_NAME: \`%s\`" "${OS_NAME}"
                exit 1
        esac

        printf "creating package \`%s\` for the release binary...\n" "${PKG_NAME}${PKG_SUFFIX}"

        cd ./target/release/ || exit 1
        rm -f -- *"${PKG_SUFFIX}"
        ${ARCHIVE_CMD} "${PKG_NAME}${PKG_SUFFIX}" "gotts${BIN_SUFFIX}"
        ls -ls -- *${PKG_SUFFIX} | cut -d' ' -f6-
        [[ "$OS_NAME" = "linux" || "$OS_NAME" = "osx" ]] && shasum "${PKG_NAME}${PKG_SUFFIX}" > "${PKG_NAME}${PKG_SUFFIX}-shasum.txt"
        [ "$OS_NAME" = "windows" ] && CertUtil -hashfile "${PKG_NAME}${PKG_SUFFIX}" SHA256 > "${PKG_NAME}${PKG_SUFFIX}-shasum.txt"
        ls -ls -- *-shasum.txt | cut -d' ' -f6-
        cd - > /dev/null || exit 1

        printf "%s package \`%s\` generated\n" "${OS_NAME}" "${PKG_NAME}${PKG_SUFFIX}"

        ;;
esac
