[package]
name = "gotts_util"
version = "0.0.6"
authors = ["Gotts Developers <gotts.tech@lists.launchpad.net>"]
description = "Simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/gottstech/gotts"
keywords = [ "crypto", "gotts", "mimblewimble" ]
workspace = ".."
edition = "2018"

[dependencies]
backtrace = "0.3"
base64 = "0.11"
byteorder = "1"
hex = "0.4"
lazy_static = "1"
rand = "0.7"
serde = "1"
serde_derive = "1"
log4rs = { version = "0.10", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
log = "0.4"
walkdir = "2"
zip = { version = "0.5", default-features = false }
parking_lot = {version = "0.10"}
zeroize = "0.9"

[dependencies.gotts_secp256k1zkp]
git = "https://github.com/gottstech/rust-secp256k1-zkp"
#path = "../../rust-secp256k1-zkp"
#version = "0.7.10"
rev = "babb0a4"
